// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khazxwlqjhynjkimqxzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoYXp4d2xxamh5bmpraW1xeHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDQxNzksImV4cCI6MjA3MjYyMDE3OX0.5OfJ2cZSvDjnnGGnMekgzvvggHFJzjn2IYaBPcz3GKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});